import {
    type Buy,
    type ConsumableItem, 
    type Dialog, 
    type DialogResponse, 
    type InteractOption, 
    type Interactible, 
    type InteractiblesItem,
    type InteractiblesOption,
    type Item,
    type ItemTypes,
    type ItemCategory,
    type DataLocation,
    type LocationContent,
    type LocationPath,
    type RequiredItems,
    type Shops,
    type Trade,
    type Trades,
    type TradeInteractible,
    type TradesInteractible,
    type End,
    type Weapon,
    type NpcContent
} from "./data";

export type {
    Buy,
    ConsumableItem,
    Dialog,
    DialogResponse,
    InteractOption,
    Interactible,
    InteractiblesItem,
    InteractiblesOption,
    Item,
    ItemTypes,
    ItemCategory,
    DataLocation,
    LocationContent,
    LocationPath,
    RequiredItems,
    Shops,
    Trade,
    Trades,
    TradeInteractible,
    TradesInteractible,
    End,
    Weapon,
    NpcContent
}