// <auto-generated />
using GameBook.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameBook.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208200047_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ConsumableItems", b =>
                {
                    b.Property<int>("ConsumableItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnergyValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiationValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumableItemID");

                    b.ToTable("ConsumableItems");
                });

            modelBuilder.Entity("GameBook.Server.Models.InteractibleOptions", b =>
                {
                    b.Property<int>("InteractibleOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OtionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractibleOptionID");

                    b.ToTable("InteractibleOptions");
                });

            modelBuilder.Entity("GameBook.Server.Models.Interactibles", b =>
                {
                    b.Property<int>("InteractibleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InteractibleID");

                    b.ToTable("Interactibles");
                });

            modelBuilder.Entity("GameBook.Server.Models.InteractiblesItems", b =>
                {
                    b.Property<int>("InteractibleItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractibleItemID");

                    b.ToTable("InteractiblesItems");
                });

            modelBuilder.Entity("GameBook.Server.Models.LocationContent", b =>
                {
                    b.Property<int>("LocationContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YPos")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationContentID");

                    b.ToTable("LocationContent");
                });

            modelBuilder.Entity("GameBook.Server.Models.LocationPaths", b =>
                {
                    b.Property<int>("PathID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnergyTravelCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstNodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondNodeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PathID");

                    b.ToTable("LocationPaths");
                });

            modelBuilder.Entity("GameBook.Server.Models.Locations", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadiationGain")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GameBook.Server.Models.NpcDialog", b =>
                {
                    b.Property<int>("DialogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DialogOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogID");

                    b.ToTable("NpcDialog");
                });

            modelBuilder.Entity("GameBook.Server.Models.NpcDialogResponses", b =>
                {
                    b.Property<int>("DialogResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DialogID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipEffect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogResponseID");

                    b.ToTable("NpcDialogResponses");
                });

            modelBuilder.Entity("GameBook.Server.Models.OptionsEnum", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OptionID");

                    b.ToTable("OptionsEnum");
                });

            modelBuilder.Entity("ItemCategories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("Items", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stackable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
