// <auto-generated />
using GameBook.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameBook.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GameBook.Server.Models.DataConsumableItem", b =>
                {
                    b.Property<int>("ConsumableItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnergyValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiationValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumableItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("ConsumableItems");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataDialog", b =>
                {
                    b.Property<int>("DialogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromInteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextDialogID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogID");

                    b.HasIndex("FromInteractibleID");

                    b.HasIndex("IteractibleID");

                    b.HasIndex("NextDialogID");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataDialogResponse", b =>
                {
                    b.Property<int>("DialogResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DialogID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextDialogID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipEffect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DialogResponseID");

                    b.HasIndex("DialogID");

                    b.HasIndex("NextDialogID");

                    b.ToTable("DialogResponses");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataEnd", b =>
                {
                    b.Property<int>("EndID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EndID");

                    b.ToTable("Ends");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OptionID");

                    b.ToTable("InteractOptions");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractible", b =>
                {
                    b.Property<int>("InteractibleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InteractibleID");

                    b.ToTable("Interactibles");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractiblesItem", b =>
                {
                    b.Property<int>("InteractiblesItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractiblesItemID");

                    b.HasIndex("InteractibleID");

                    b.HasIndex("ItemId");

                    b.ToTable("InteractiblesItems");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractiblesOption", b =>
                {
                    b.Property<int>("InteractiblesOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InteractiblesOptionID");

                    b.HasIndex("InteractibleID");

                    b.HasIndex("OptionID");

                    b.ToTable("InteractiblesOptions");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stackable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataItemCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocation", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadiationGain")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocationContent", b =>
                {
                    b.Property<int>("LocationContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InteractibleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YPos")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationContentID");

                    b.HasIndex("InteractibleID");

                    b.HasIndex("LocationID");

                    b.ToTable("LocationContents");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocationPath", b =>
                {
                    b.Property<int>("PathID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnergyTravelCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstNodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondNodeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PathID");

                    b.HasIndex("FirstNodeID");

                    b.HasIndex("SecondNodeID");

                    b.ToTable("LocationPaths");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataRequiredItems", b =>
                {
                    b.Property<int>("RequiredItemsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequiredItemsID");

                    b.HasIndex("ItemID");

                    b.HasIndex("LocationID");

                    b.ToTable("RequiredItems");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataConsumableItem", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataDialog", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataInteractible", "FromInteractible")
                        .WithMany()
                        .HasForeignKey("FromInteractibleID");

                    b.HasOne("GameBook.Server.Models.DataInteractible", "Interactible")
                        .WithMany()
                        .HasForeignKey("IteractibleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataDialog", "NextDialog")
                        .WithMany()
                        .HasForeignKey("NextDialogID");

                    b.Navigation("FromInteractible");

                    b.Navigation("Interactible");

                    b.Navigation("NextDialog");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataDialogResponse", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataDialog", "Dialog")
                        .WithMany("DialogResponses")
                        .HasForeignKey("DialogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataDialog", "NextDialog")
                        .WithMany()
                        .HasForeignKey("NextDialogID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dialog");

                    b.Navigation("NextDialog");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractiblesItem", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataInteractible", "Interactible")
                        .WithMany()
                        .HasForeignKey("InteractibleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactible");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractiblesOption", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataInteractible", "Interactible")
                        .WithMany("InteractOptions")
                        .HasForeignKey("InteractibleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataInteractOption", "Option")
                        .WithMany("Interactibles")
                        .HasForeignKey("OptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactible");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataItem", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocationContent", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataInteractible", "Interactible")
                        .WithMany("LocationContents")
                        .HasForeignKey("InteractibleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataLocation", "Location")
                        .WithMany("LocationContents")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactible");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocationPath", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataLocation", "FirstNode")
                        .WithMany()
                        .HasForeignKey("FirstNodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataLocation", "SecondNode")
                        .WithMany()
                        .HasForeignKey("SecondNodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstNode");

                    b.Navigation("SecondNode");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataRequiredItems", b =>
                {
                    b.HasOne("GameBook.Server.Models.DataItem", "Item")
                        .WithMany("RequiredInLocations")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameBook.Server.Models.DataLocation", "Location")
                        .WithMany("RequiredItems")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataDialog", b =>
                {
                    b.Navigation("DialogResponses");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractOption", b =>
                {
                    b.Navigation("Interactibles");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataInteractible", b =>
                {
                    b.Navigation("InteractOptions");

                    b.Navigation("LocationContents");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataItem", b =>
                {
                    b.Navigation("RequiredInLocations");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GameBook.Server.Models.DataLocation", b =>
                {
                    b.Navigation("LocationContents");

                    b.Navigation("RequiredItems");
                });
#pragma warning restore 612, 618
        }
    }
}
